### ISSUE TITLE
llvm-flang.github.io?

### ISSUE THREAD

**Issue by ppenzin** [llvm-flang/flang#22]
Should there be a website for Flang similar in content to [clang.llvm.org](http://clang.llvm.org)? Github Pages are pretty straightforward to [use](https://help.github.com/categories/github-pages-basics/) and it would be able to serve that kind of content, though it might require manual updates (or a bot that would publish contents when they change).

**Comment by jleidel** [comment]
I would make sure that you are cognizant of the PGI Flang efforts as to not collide with their project naming/placement.

**Comment by ppenzin** [comment]
That is good concern. As for URLs, most of Nvidia's Flang pages have "flang-compiler" in the name (for example flang-compiler.org redirects to their repo), so there would not be a full collision at least at the GH Pages level.
On deeper level though, I find it confusing that both projects are named Flang, but I really don't have a good proposal on how to fix that. Seems like eventually one project would need to be renamed. What are your thoughts on this?

**Comment by jleidel** [comment]
The NVIDIA/PGI project is the official Flang project.  We made a conscious decision to release the name to the NVIDIA project as it will likely garner much more support in the long term.  As a result, if you want to continue development on this effort, I highly suggest you fork it and rename it.

**Comment by ppenzin** [comment]
That makes sense. I did not know that the name was officially released to Nvidia.

**Comment by ppenzin** [comment]
Any preference/advice for a new name? :)

**Comment by ppenzin** [comment]
As you have probably seen, I forked it as @llvm-fortran. I think it would beneficial if there is a note about it in description and readme, in case there are people eager to work on a Fortran compiler :)

**Comment by Efreak** [comment]
You want https://github.com/llvm-fortran/fort not gihub.com (I'll try to remember to submit a pull for this later, but I'm on mobile rn trying to figure out how to get a fortran compiler recognized by cmake in termux...)
