### ISSUE TITLE
Update against LLVM 8?

### ISSUE THREAD

**Issue by bingao** [llvm-flang/flang#25]
Hi,

I am interested in using flang. I wonder if it will be updated so that it can be built with LLVM 8 (which should be release in February)? Thank you.

Best regards
Bin Gao

**Comment by jleidel** [comment]
Bin, it will not.  Flang has been deprecated in favor of the official
Fortran frontend project supported by PGI/NVIDIA.

**Comment by bingao** [comment]
Hi @jleidel 

OK. But it sounds pity because I think this is a good project.

**Comment by ppenzin** [comment]
@bingao Flang (this repository and the runtime library) is forked as [fort](https://github.com/llvm-fortran/fort), and it builds against current master as well as the upcoming LLVM 8.

**Comment by bingao** [comment]
Hi @ppenzin 

Thank you. I will definitely have a try.
