### ISSUE TITLE
Distinguish from PGI's Flang and forked sources

### ISSUE THREAD

**Issue by waldyrious** [llvm-flang/flang#5]
There seem to be two projects with the same name -- this one, and [flang-compiler/flang](https://github.com/flang-compiler/flang). I've [asked there](https://github.com/flang-compiler/flang/issues/38) for clarification of the distinction, and I think it would be nice to include such a disambiguation note on this project's README as well. Would a PR doing that be considered?

Another question I have is whether this repo is now considered the canonical one for this project, since Github marks it as forked from [CodethinkLabs/flang](https://github.com/CodethinkLabs/flang), which itself is forked from [hyp/flang](https://github.com/hyp/flang), which in turn is forked from [isanbard/flang](https://github.com/isanbard/flang) (phew!). If the other ones are indeed superseded by this one, it would be nice to make that clear, e.g. with a [repostatus.org "Moved" badge](http://www.repostatus.org/#how-to-use-it).

**Comment by jleidel** [comment]
The PGI project has taken over the official PGI name as the mainline project to maintain a long-term Fortran frontend for LLVM.  Development on this project has stagnated, but I am more than willing to accept continued patches.

**Comment by waldyrious** [comment]
So they did have the same origin, or did each project start from scratch? I'm asking mostly for historical reference, as this is not clear from the repos alone (unless I'm missing something). Is there a document somewhere that describes the history of both projects and their relationship?

**Comment by zeuk** [comment]
They seem to have entirely different origins and don't seem to share any sources (just compare how they build, for example). It seems like this project has been maintained by different people over the years, just like you described in the first message.

**Comment by waldyrious** [comment]
Yeah, that's what it seemed to me as well. I'd be happy to submit a PR documenting the distinction if the details are confirmed (particularly in relation to the fork chain).

**Comment by jleidel** [comment]
The PGI port started from their own proprietary Fortran frontend source base.  The original Flang project was originally started from scratch (similar in a sense to Clang) and migrated between various developers over the years.

**Comment by waldyrious** [comment]
Since for some reason the automatic back-references weren't activated: I sent PR #6, adding a disambiguation note to the README, which was just merged. Thanks for the clarifications and the quick reaction, @jleidel :)
